Repository nextcloud/workflow_pdf_converter, pull requests merged in 2023-03, with the labels that each got.

#452 chore: Add Nextcloud 27 support on master
  appinfo/info.xml
  package.json
Labels: 4. to release

#455 add autoloading file and config
  composer.json
  composer/autoload.php
  krankerl.toml
Labels: 4. to release, backport-request, bug

#461 do not include .php-cs-fixer.dist.php in build
  .nextcloudignore
Labels: 3. to review, backport-request

#460 v1.9.1
  appinfo/info.xml
Labels: 3. to review

#465 v1.10.1
  appinfo/info.xml
Labels: 3. to review
