Repository nextcloud/workflow_pdf_converter, pull requests merged in 2024-09, with the labels that each got.

#684 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#685 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#681 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#679 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#678 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#680 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#686 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#690 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#689 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#688 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#687 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#692 [stable30] build(npm): cleanup package-lock.json
  package-lock.json
Labels: 4. to release, technical debt, dependencies

#693 ci(github): update workflows
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: backport-request

#702 [stable29] build: 1.14.1
  appinfo/info.xml
  package.json
Labels: 3. to review

#703 [stable28] build: 1.13.1
  appinfo/info.xml
  package.json
Labels: 3. to review

#705 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#704 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#710 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#709 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#708 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#711 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#714 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#713 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#715 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#716 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
