Repository nextcloud/workflow_pdf_converter, pull requests merged in 2024-04, with the labels that each got.

#593 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#591 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#579 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#592 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#600 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#599 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#601 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#603 build(dev-deps): update eslint in one go
  package-lock.json
Labels: 3. to review

#605 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#604 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#606 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#612 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#611 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#610 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies
