Repository nextcloud/workflow_pdf_converter, pull requests merged in 2024-03, with the labels that each got.

#575 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#584 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#585 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#583 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#587 ci(deps-dev): fix requiring nc-ocp
  composer.json
  composer.lock
  lib/BackgroundJobs/Convert.php
Labels: 3. to review

#577 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated
