Repository nextcloud/workflow_pdf_converter, pull requests merged in 2025-01, with the labels that each got.

#769 deps: downgrade nc/vue for a regression, update other deps
  package-lock.json
  package.json
Labels: 3. to review, bug

#770 build(release): 1.15.1
  appinfo/info.xml
Labels: 3. to review

#771 build(release): 1.14.2
  appinfo/info.xml
Labels: 3. to review

#774 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#776 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#773 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#775 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#777 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#781 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#780 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#782 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#783 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
